/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facultyfeedbacksystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AddStudent extends javax.swing.JFrame implements UpdateDB_Interface {
    Connection con;
    private String firstName, lastName, uname, s_class,password, email; //to store the details given in the text fields
    private int sID;
    private static final String category = "student";
   // ArrayList<String> subjects = new ArrayList<String>(); 
    String subjects[]=new String[14];
    /* ArrayList to store 
        Use of array list instead of array because arraylist is dynamic 
        data structure where the length of the arraylist can be changed throughout the code.
        Each student has different subject combinations so this is the best way to store their subjects  
    */
    
    /**
     * Creates new form AddStudent_Coordinator
     */
    public AddStudent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        Save_btn = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fname_txt = new javax.swing.JTextField();
        student_id = new javax.swing.JTextField();
        reset_btn = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        student_class = new javax.swing.JComboBox<>();
        jPanel29 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        c10 = new javax.swing.JCheckBox();
        lname_txt = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        generate_btn = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        uname_txt = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pwd_txt = new javax.swing.JPasswordField();
        back_btn1 = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        c11 = new javax.swing.JCheckBox();
        c12 = new javax.swing.JCheckBox();
        c13 = new javax.swing.JCheckBox();
        c14 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/feedback image2.jpeg"))); // NOI18N
        jLabel6.setText("jLabel4");

        jPanel14.setBackground(new java.awt.Color(0, 0, 63));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));

        Save_btn.setBackground(new java.awt.Color(255, 183, 76));
        Save_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Save_btn.setForeground(new java.awt.Color(0, 0, 153));
        Save_btn.setText("Save");
        Save_btn.setEnabled(false);
        Save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_btnActionPerformed(evt);
            }
        });

        jPanel22.setBackground(new java.awt.Color(255, 183, 76));

        jLabel7.setBackground(new java.awt.Color(255, 183, 76));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("FIRST NAME");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel27.setBackground(new java.awt.Color(255, 183, 76));

        jLabel8.setBackground(new java.awt.Color(255, 183, 76));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("STUDENT ID");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fname_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_txtActionPerformed(evt);
            }
        });

        student_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        student_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_idActionPerformed(evt);
            }
        });

        reset_btn.setBackground(new java.awt.Color(255, 183, 76));
        reset_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(0, 0, 153));
        reset_btn.setText("RESET");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        jPanel31.setBackground(new java.awt.Color(255, 183, 76));

        jLabel12.setBackground(new java.awt.Color(255, 183, 76));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("STUDENT CLASS");

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        student_class.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        student_class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IBDP 1", "IBDP 2" }));

        jPanel29.setBackground(new java.awt.Color(255, 183, 76));

        jLabel10.setBackground(new java.awt.Color(255, 183, 76));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("SUBJECTS");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        c1.setBackground(new java.awt.Color(0, 0, 63));
        c1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setText("English");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.setBackground(new java.awt.Color(0, 0, 63));
        c2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setText("Mathematics");

        c3.setBackground(new java.awt.Color(0, 0, 63));
        c3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setText("Physics");

        c5.setBackground(new java.awt.Color(0, 0, 63));
        c5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c5.setForeground(new java.awt.Color(255, 255, 255));
        c5.setText("Computer Science");

        c4.setBackground(new java.awt.Color(0, 0, 63));
        c4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setText("Chemistry");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        c8.setBackground(new java.awt.Color(0, 0, 63));
        c8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c8.setForeground(new java.awt.Color(255, 255, 255));
        c8.setText("Psychology");

        c6.setBackground(new java.awt.Color(0, 0, 63));
        c6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setText("French");

        c7.setBackground(new java.awt.Color(0, 0, 63));
        c7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c7.setForeground(new java.awt.Color(255, 255, 255));
        c7.setText("Hindi");

        c9.setBackground(new java.awt.Color(0, 0, 63));
        c9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c9.setForeground(new java.awt.Color(255, 255, 255));
        c9.setText("Business Management");

        c10.setBackground(new java.awt.Color(0, 0, 63));
        c10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c10.setForeground(new java.awt.Color(255, 255, 255));
        c10.setText("Visual Arts");

        lname_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel23.setBackground(new java.awt.Color(255, 183, 76));

        jLabel9.setBackground(new java.awt.Color(255, 183, 76));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("LAST NAME");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        generate_btn.setBackground(new java.awt.Color(255, 183, 76));
        generate_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generate_btn.setForeground(new java.awt.Color(0, 0, 153));
        generate_btn.setText("GENERATE LOGIN CREDENTIALS");
        generate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_btnActionPerformed(evt);
            }
        });

        jPanel30.setBackground(new java.awt.Color(255, 183, 76));

        jLabel11.setBackground(new java.awt.Color(255, 183, 76));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("USERNAME");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        uname_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel32.setBackground(new java.awt.Color(255, 183, 76));

        jLabel13.setBackground(new java.awt.Color(255, 183, 76));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("PASSWORD");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pwd_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        back_btn1.setBackground(new java.awt.Color(255, 183, 76));
        back_btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back_btn1.setForeground(new java.awt.Color(0, 0, 153));
        back_btn1.setText("BACK");
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });

        jPanel33.setBackground(new java.awt.Color(255, 183, 76));

        jLabel14.setBackground(new java.awt.Color(255, 183, 76));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("EMAIL ID");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        email_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });

        c11.setBackground(new java.awt.Color(0, 0, 63));
        c11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c11.setForeground(new java.awt.Color(255, 255, 255));
        c11.setText("Economics");
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });

        c12.setBackground(new java.awt.Color(0, 0, 63));
        c12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c12.setForeground(new java.awt.Color(255, 255, 255));
        c12.setText("Biology");

        c13.setBackground(new java.awt.Color(0, 0, 63));
        c13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c13.setForeground(new java.awt.Color(255, 255, 255));
        c13.setText("History");

        c14.setBackground(new java.awt.Color(0, 0, 63));
        c14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c14.setForeground(new java.awt.Color(255, 255, 255));
        c14.setText("Global Politics");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addComponent(c1)
                                        .addGap(18, 18, 18)
                                        .addComponent(c2))
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addComponent(c11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c7)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c4)
                                        .addGap(18, 18, 18)
                                        .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c6))
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(c8)
                                        .addGap(18, 18, 18)
                                        .addComponent(c9)
                                        .addGap(18, 18, 18)
                                        .addComponent(c10))))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(c12)
                                .addGap(18, 18, 18)
                                .addComponent(c13)
                                .addGap(26, 26, 26)
                                .addComponent(c14))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lname_txt)
                                    .addComponent(fname_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(uname_txt)))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(generate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(student_class, 0, 160, Short.MAX_VALUE)
                            .addComponent(student_id)
                            .addComponent(pwd_txt)
                            .addComponent(email_txt))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fname_txt)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_class, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_txt)
                    .addComponent(uname_txt))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(generate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email_txt)
                            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c1)
                            .addComponent(c3)
                            .addComponent(c2)
                            .addComponent(c4)
                            .addComponent(c5)
                            .addComponent(c6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c7)
                            .addComponent(c8)
                            .addComponent(c9)
                            .addComponent(c10)
                            .addComponent(c11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c12)
                            .addComponent(c13)
                            .addComponent(c14))
                        .addGap(31, 31, 31)))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_btnActionPerformed
        if (this.validateEntries()) {
            updateRecordsDB();
        }
    }//GEN-LAST:event_Save_btnActionPerformed
    public boolean validateEntries() {
        s_class = student_class.getSelectedItem().toString();
        if (fname_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "First name  cannot be left blank.");
            return false;
        } else {
            firstName = fname_txt.getText();
        }
        
        if (lname_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Last Name cannot be left blank.");
            return false;
        } else {
            lastName = lname_txt.getText();
        }

        if (student_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID cannot be left blank.");
            return false;
        } else {
            sID = Integer.parseInt(student_id.getText());
        }
        
        if (pwd_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password cannot be left blank.");
            return false;
        } else {
            password = pwd_txt.getText();
        }

        

        if (email_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email cannot be left blank.");
            return false;
        } else {
            String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(this.email_txt.getText());
            if (matcher.matches() == false) {
                boolean flag = false;
                JOptionPane.showMessageDialog(this, "Invalid Email");
                return false;
            }
            email = email_txt.getText();
        }

        //c1,c2,...,c13 are the names of the check boxes next to the subject
        int counter = 0; //to maintain the index of the subjects array
        if (c1.isSelected()) { 
            subjects[counter]="English";
            counter++;
        }

        if (c2.isSelected()) {
            subjects[counter]="Mathematics";
            counter++;
        }

        if (c3.isSelected()) {
            subjects[counter]="Physics";
            counter++;
        }

        if (c4.isSelected()) {
            subjects[counter]="Chemistry";
            counter++;
        }

        if (c5.isSelected()) {
            subjects[counter]="Computer Science";
            counter++;
        }

        if (c6.isSelected()) {
            subjects[counter]="French";
            counter++;
        }

        if (c7.isSelected()) {
            subjects[counter]="Hindi";
            counter++;
        }

        if (c8.isSelected()) {
            subjects[counter]="Psychology";
            counter++;
        }

        if (c9.isSelected()) {
            subjects[counter]="Business Management";
            counter++;
        }

        if (c10.isSelected()) {
            subjects[counter]="Visual Arts";
            counter++;
        }

        if (c11.isSelected()) {
            subjects[counter]="Economics";
            counter++;
        }

        if (c12.isSelected()) {
           subjects[counter]="Biology";
            counter++;
        }

        if (c13.isSelected()) {
            subjects[counter]="History";
            counter++;
        }

        if (c14.isSelected()) {
            subjects[counter]="Global Politics";
            counter++;
        }
    
        /*Validation
        A student can only take upto 6 subjects in IBDP and therefore this if else statement is used.
        If the user choses more than or less than 6 subjects, an error message will be shown.
         */
        if (counter == 6) {
            return true;
        } else if (counter > 6) {
            JOptionPane.showMessageDialog(this, "More than 6 subjects are not allowed. Please select only 6 subjects.");
            return false;
        } else {
            JOptionPane.showMessageDialog(this, "Less than 6 subjects are not allowed. Please select only 6 subjects.");
            return false;
        }
    }
    private void fname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_txtActionPerformed

    private void student_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_idActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        fname_txt.setText("");
        student_id.setText("");
        lname_txt.setText("");
        uname_txt.setText("");
        pwd_txt.setText("");
        email_txt.setText("");
    }//GEN-LAST:event_reset_btnActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void generate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_btnActionPerformed
        //to generate a unique username, the unique id is used and added to the name of the student
        uname_txt.setText(fname_txt.getText() + student_id.getText());
        this.Save_btn.setEnabled(true);
    }//GEN-LAST:event_generate_btnActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        HomePage_Coordinator mp = new HomePage_Coordinator();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save_btn;
    private javax.swing.JButton back_btn1;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c12;
    private javax.swing.JCheckBox c13;
    private javax.swing.JCheckBox c14;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JButton generate_btn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JPasswordField pwd_txt;
    private javax.swing.JButton reset_btn;
    private javax.swing.JComboBox<String> student_class;
    private javax.swing.JTextField student_id;
    private javax.swing.JTextField uname_txt;
    // End of variables declaration//GEN-END:variables

    @Override
    //this method adds the newly added details of the student to the student_details_tbl and the login credentials to the login_tbl
    public void updateRecordsDB() { 
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DatabaseConnection.getConnect();//Uses(Association) relationship
            Statement st = con.createStatement();
            Statement st1 = con.createStatement();
            int x = st.executeUpdate("insert into student_details_tbl  values('" + sID + "','" + this.firstName + "','" + 
                    this.lastName + "','" + this.s_class + "'," + "'" + subjects[0] + "','" + subjects[1] + "','" + 
                    subjects[2] + "','" + subjects[3] + "','" + subjects[4] + "','" + subjects[5] + "')"); 
            int y = st1.executeUpdate("insert into login_tbl values(" + this.sID + ",'" + this.firstName + "','" 
                    + this.lastName + "','" + this.uname_txt.getText() + "','" + this.password + "','" + category + "','"
                    + this.email+"')"); 
            if (x > 0 && y > 0) {
                JOptionPane.showMessageDialog(this, "Congratulations! Your records are added to the database successfully"); 
                MainPage mp = new MainPage();
                mp.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}



