/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facultyfeedbacksystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sunishka Sharma
 */
public class HomePage_Coordinator extends javax.swing.JFrame {

    /**
     * Creates new form HomePage_Coordinator
     */
    public HomePage_Coordinator() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Log_out = new javax.swing.JButton();
        change_pwd_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        add_teacher_btn = new javax.swing.JButton();
        delete_s_btn1 = new javax.swing.JButton();
        view_teachers_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        add_student_btn = new javax.swing.JButton();
        view_students_btn = new javax.swing.JButton();
        delete_s_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        view_sug_btn = new javax.swing.JButton();
        view_feedback_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 63));

        Log_out.setBackground(new java.awt.Color(255, 183, 76));
        Log_out.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Log_out.setForeground(new java.awt.Color(0, 0, 153));
        Log_out.setText("Log Out");
        Log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_outActionPerformed(evt);
            }
        });

        change_pwd_btn.setBackground(new java.awt.Color(255, 183, 76));
        change_pwd_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        change_pwd_btn.setForeground(new java.awt.Color(0, 0, 153));
        change_pwd_btn.setText("CHANGE PASSWORD");
        change_pwd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_pwd_btnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        add_teacher_btn.setBackground(new java.awt.Color(255, 183, 76));
        add_teacher_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_teacher_btn.setForeground(new java.awt.Color(0, 0, 153));
        add_teacher_btn.setText("ADD TEACHER");
        add_teacher_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_teacher_btnActionPerformed(evt);
            }
        });

        delete_s_btn1.setBackground(new java.awt.Color(255, 183, 76));
        delete_s_btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete_s_btn1.setForeground(new java.awt.Color(0, 0, 153));
        delete_s_btn1.setText("DELETE TEACHER");
        delete_s_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_s_btn1ActionPerformed(evt);
            }
        });

        view_teachers_btn.setBackground(new java.awt.Color(255, 183, 76));
        view_teachers_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_teachers_btn.setForeground(new java.awt.Color(0, 0, 153));
        view_teachers_btn.setText("VIEW TEACHERS");
        view_teachers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_teachers_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_teachers_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_s_btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_teacher_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(add_teacher_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(view_teachers_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_s_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        add_student_btn.setBackground(new java.awt.Color(255, 183, 76));
        add_student_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_student_btn.setForeground(new java.awt.Color(0, 0, 153));
        add_student_btn.setText("ADD STUDENT");
        add_student_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_student_btnActionPerformed(evt);
            }
        });

        view_students_btn.setBackground(new java.awt.Color(255, 183, 76));
        view_students_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_students_btn.setForeground(new java.awt.Color(0, 0, 153));
        view_students_btn.setText("VIEW STUDENTS");
        view_students_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_students_btnActionPerformed(evt);
            }
        });

        delete_s_btn.setBackground(new java.awt.Color(255, 183, 76));
        delete_s_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete_s_btn.setForeground(new java.awt.Color(0, 0, 153));
        delete_s_btn.setText("DELETE STUDENT");
        delete_s_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_s_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(add_student_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_students_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_s_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(add_student_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(view_students_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(delete_s_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        view_sug_btn.setBackground(new java.awt.Color(255, 183, 76));
        view_sug_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_sug_btn.setForeground(new java.awt.Color(0, 0, 153));
        view_sug_btn.setText("VIEW SUGGESTION BOX");
        view_sug_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_sug_btnActionPerformed(evt);
            }
        });

        view_feedback_btn.setBackground(new java.awt.Color(255, 183, 76));
        view_feedback_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_feedback_btn.setForeground(new java.awt.Color(0, 0, 153));
        view_feedback_btn.setText("VIEW FEEDBACK");
        view_feedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_feedback_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_sug_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_feedback_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(view_sug_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_feedback_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(change_pwd_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Log_out)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_pwd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/feedback image2.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_teacher_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_teacher_btnActionPerformed
        AddTeacher_Coordinator teacher = new AddTeacher_Coordinator();
        teacher.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_teacher_btnActionPerformed

    private void view_feedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_feedback_btnActionPerformed
        ViewTeacherFeedback_Coordinator feedback;
        try {
            feedback = new ViewTeacherFeedback_Coordinator();
            feedback.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage_Coordinator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_view_feedback_btnActionPerformed

    private void view_sug_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_sug_btnActionPerformed
        ViewSuggestion_Coordinator sug = new ViewSuggestion_Coordinator();
        sug.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_view_sug_btnActionPerformed

    private void Log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_outActionPerformed
        MainPage ch = new MainPage();
        ch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Log_outActionPerformed

    private void add_student_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_student_btnActionPerformed
        AddStudent st = new AddStudent();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_student_btnActionPerformed

    private void change_pwd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pwd_btnActionPerformed
        ChangePassword_Coordinator cha = new ChangePassword_Coordinator();
        cha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_change_pwd_btnActionPerformed

    private void delete_s_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_s_btnActionPerformed
        DeleteStudent_Coordinator de = new DeleteStudent_Coordinator();
        de.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_delete_s_btnActionPerformed

    private void view_students_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_students_btnActionPerformed
        ViewStudents_Coordinator s = new ViewStudents_Coordinator();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_view_students_btnActionPerformed

    private void delete_s_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_s_btn1ActionPerformed
        DeleteTeacher_Coordinator de = new DeleteTeacher_Coordinator();
        de.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_delete_s_btn1ActionPerformed

    private void view_teachers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_teachers_btnActionPerformed
        ViewTeachers_Coordinator vi = new ViewTeachers_Coordinator();
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_view_teachers_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage_Coordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage_Coordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage_Coordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage_Coordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage_Coordinator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Log_out;
    private javax.swing.JButton add_student_btn;
    private javax.swing.JButton add_teacher_btn;
    private javax.swing.JButton change_pwd_btn;
    private javax.swing.JButton delete_s_btn;
    private javax.swing.JButton delete_s_btn1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton view_feedback_btn;
    private javax.swing.JButton view_students_btn;
    private javax.swing.JButton view_sug_btn;
    private javax.swing.JButton view_teachers_btn;
    // End of variables declaration//GEN-END:variables
}
