/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facultyfeedbacksystem;

import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunishka Sharma
 */
public class ViewTeacherFeedback_Coordinator extends javax.swing.JFrame {
    Connection con = null;
    DatabaseConnection obj = new DatabaseConnection();
    DefaultTableModel data;
    private String teacher_name;
    private int teacher_id;
   
    public ViewTeacherFeedback_Coordinator() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null); //to set the position at center
        con = obj.getConnect();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = obj.getConnect();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery("select * from teacher_details_tbl");
            //fetching data from teachers_details_tbl and putting it in the combo box
            while (r.next()) {
                String name = r.getString(2);
                teacher_name_combo.addItem(name);
            }
            con.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    //gets the teacher id which will be used to calculate the average feedback score for the teacher
    public int getTeacherID() {
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = obj.getConnect();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery("select * from teacher_details_tbl where teacher_name='" + 
                    teacher_name_combo.getSelectedItem().toString() + "'"); 
            while (r.next()) {
                this.teacher_id = r.getInt(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return this.teacher_id;
    }
    
    //gets the student id which will be used to calculate total number of students who have given the feedback
    public String getStudentName(int id) {
        String fname, lname, name = null;
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = obj.getConnect();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery("select first_name,last_name from student_details_tbl where admission_no=" + id + "");
            while (r.next()) {
                fname = r.getString(1);
                lname = r.getString(2);
                name = fname + " " + lname;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return name;
    }

    //gets the question id which will be used to calculate the average feedback score for each question
    public String getQuestion(int qid) {
        String question = null;
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = obj.getConnect();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery("select question from questions_tbl where question_id=" + qid + "");
            while (r.next()) {
                question = r.getString(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return question;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        generate_report_btn = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacher_table = new javax.swing.JTable();
        teacher_name_combo = new javax.swing.JComboBox<>();
        back_btn1 = new javax.swing.JButton();
        check_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/feedback image2.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jPanel42.setBackground(new java.awt.Color(0, 0, 63));
        jPanel42.setForeground(new java.awt.Color(255, 255, 255));

        generate_report_btn.setBackground(new java.awt.Color(255, 183, 76));
        generate_report_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generate_report_btn.setForeground(new java.awt.Color(0, 0, 153));
        generate_report_btn.setText("GENERATE REPORT");
        generate_report_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_report_btnActionPerformed(evt);
            }
        });

        jPanel23.setBackground(new java.awt.Color(255, 183, 76));

        jLabel8.setBackground(new java.awt.Color(255, 183, 76));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("TEACHER NAME");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        teacher_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacher_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Name", "Question", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(teacher_table);

        teacher_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_name_comboActionPerformed(evt);
            }
        });

        back_btn1.setBackground(new java.awt.Color(255, 183, 76));
        back_btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back_btn1.setForeground(new java.awt.Color(0, 0, 153));
        back_btn1.setText("BACK");
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });

        check_btn.setText("Check");
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(teacher_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(check_btn)
                        .addGap(69, 69, 69)
                        .addComponent(generate_report_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 419, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                    .addContainerGap(1005, Short.MAX_VALUE)
                    .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(203, 203, 203)))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teacher_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(check_btn)
                        .addComponent(generate_report_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                    .addContainerGap(365, Short.MAX_VALUE)
                    .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generate_report_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_report_btnActionPerformed
        
        
        FeedbackReport back=new FeedbackReport(this.getTeacherID(), this.teacher_name_combo.getSelectedItem().toString());
        this.dispose();
    }//GEN-LAST:event_generate_report_btnActionPerformed
    
    private void teacher_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_name_comboActionPerformed
        
       
    }//GEN-LAST:event_teacher_name_comboActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        HomePage_Coordinator back = new HomePage_Coordinator();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        this.teacher_id = this.getTeacherID();
        int studentID, quesID, score;
        String question, studentName;
       
        try {
            data = (DefaultTableModel) teacher_table.getModel();
            data.setRowCount(0);
            teacher_table.getColumnModel().getColumn(0).setMaxWidth(300);
            teacher_table.getColumnModel().getColumn(0).setMinWidth(300);
            teacher_table.getColumnModel().getColumn(1).setMaxWidth(700);
            teacher_table.getColumnModel().getColumn(1).setMinWidth(700);
            teacher_table.getColumnModel().getColumn(2).setMaxWidth(50);
            teacher_table.getColumnModel().getColumn(2).setMinWidth(50);
            Class.forName("java.sql.DriverManager");
            Connection con = obj.getConnect();
            Statement st = con.createStatement();
            ResultSet r = st.executeQuery("select * from teacher_feedback_tbl where teacher_id=" + this.getTeacherID() + "");
            //reusability for this.getTeacherID()
            while (r.next()) {
                studentID = r.getInt(2);
                studentName = this.getStudentName(studentID);
                quesID = r.getInt(3);
                question = this.getQuestion(quesID);
                score = r.getInt(4);
                data.addRow(new Object[]{studentName, question, score});
                System.out.println("student id :" + studentID + "--" + quesID + "---" + score);
            }
            r.close();
            st.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
       
      
       
     
    }//GEN-LAST:event_check_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherFeedback_Coordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherFeedback_Coordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherFeedback_Coordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherFeedback_Coordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewTeacherFeedback_Coordinator().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewTeacherFeedback_Coordinator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn1;
    private javax.swing.JButton check_btn;
    private javax.swing.JButton generate_report_btn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> teacher_name_combo;
    private javax.swing.JTable teacher_table;
    // End of variables declaration//GEN-END:variables
}
